ignore_unreachable_actions:
- devise/confirmations#create
- devise/confirmations#new
- devise/confirmations#show
- devise/omniauth_callbacks#failure
- devise/omniauth_callbacks#passthru
- devise/passwords#new
- devise/passwords#update
- devise/passwords#create
- devise/passwords#edit
- devise/registrations#cancel
- devise/registrations#create
- devise/registrations#destroy
- devise/registrations#edit
- devise/registrations#new
- devise/registrations#update
- devise/unlocks#create
- devise/unlocks#new
- devise/unlocks#show
- devise#_prefixes

ignore_unused_routes:
