#!/bin/bash
set -e

echo "Waiting for database before starting rails..."
./wait-for-it.sh db:5432

bin/bundle install

RAILS_ENV=development bin/rails db:create
RAILS_ENV=development bin/rails db:migrate

rm -f /usr/app/landgrab/tmp/pids/server.pid

# bundle exec puma -C config/puma.rbexec "$@"
RAILS_ENV=development bin/rails s -b 0.0.0.0

